In [24]:
import numpy as np

np.random.seed(42)
marks = np.random.randint(0, 100, size = 50)

print(marks)

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32 75 57 21 88 48 90 58 41 91 59 79 14 61 61 46 61 50 54 63  2 50  6 20
 72 38]


In [25]:
# Mean, Median, Lowest, Highest and Std 
mean = np.mean(marks)
median = np.median(marks)
lowest = np.min(marks)
highest = np.max(marks)
std_dev = np.std(marks)

print(f"Avg Marks : {mean}")
print(f"Median : {median}")
print(f"Lowest Score : {lowest}")
print(f"Highest Score : {highest}")
print(f"Std Deviation : {std_dev: .2f}")

Avg Marks : 50.84
Median : 55.5
Lowest Score : 1
Highest Score : 99
Std Deviation :  27.85


In [26]:
fail = marks[marks < 40]
dist = marks[marks > 85]
        
print(f"Failed Students : {len(fail)} -> Scores : {fail}")
print(f"Merit Students : {len(dist)} -> Scores : {dist}")   

Failed Students : 17 -> Scores : [14 20 23  2 21  1 29 37  1 20 32 21 14  2  6 20 38]
Merit Students : 8 -> Scores : [92 86 87 99 87 88 90 91]


In [37]:
# Normalization between 0 to 1
normalized = (marks - lowest) / (highest - lowest)
print(f"Normalized : {np.round(normalized, 2)}")

Normalized : [0.51 0.93 0.13 0.71 0.6  0.19 0.83 0.87 0.74 0.74 0.88 1.   0.22 0.01
 0.2  0.52 0.   0.88 0.29 0.37 0.   0.63 0.59 0.19 0.32 0.76 0.57 0.2
 0.89 0.48 0.91 0.58 0.41 0.92 0.59 0.8  0.13 0.61 0.61 0.46 0.61 0.5
 0.54 0.63 0.01 0.5  0.05 0.19 0.72 0.38]


In [38]:
# Reshaped array
reshaped = marks.reshape(5, 10)
row_avg = np.mean(reshaped, axis = 1)
col_avg = np.mean(reshaped, axis = 0)

print(f"Reshaped : {reshaped}")
print(f"Avg of every subject : {np.round(row_avg, 2)}")
print(f"Avg of every student : {np.round(col_avg, 2)}")

Reshaped : [[51 92 14 71 60 20 82 86 74 74]
 [87 99 23  2 21 52  1 87 29 37]
 [ 1 63 59 20 32 75 57 21 88 48]
 [90 58 41 91 59 79 14 61 61 46]
 [61 50 54 63  2 50  6 20 72 38]]
Avg of every subject : [62.4 43.8 46.4 60.  41.6]
Avg of every student : [58.  72.4 38.2 49.4 34.8 55.2 32.  55.  64.8 48.6]


In [41]:
# Weighted Score
theory = marks[:25]
practical = marks[25:]

weighted_score = (0.4 * theory) + (0.6 * practical)
print(f"Weigted Score : {np.round(weighted_score, 2)}")
print(f"Weigted Avg Score : {np.mean(weighted_score): .2f}")

Weigted Score : [65.4 71.  18.2 81.2 52.8 62.  67.6 59.  84.2 65.  82.2 48.  45.8 37.4
 36.  57.4 30.4 67.2 49.4 16.  30.4 28.8 35.6 51.2 35.6]
Weigted Avg Score :  51.11
